### ISSUE TITLE
Parser throws ArgumentOutOfRangeExceptionexception when name has parenthesis (just nickname)

### ISSUE THREAD

**Issue by drgraduss** [aeshirey/NameParserSharp#8]
If name has parenthesis you get `ArgumentOutOfRangeException` exception. i.e.

`var humanName = new HumanName("(FIRSTNAME MIDDLENAME LASTNAME)");`

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at System.Collections.Generic.List`1.get_Item(Int32 index)
at NameParser.HumanName.ParseFullName() in c:\Users\Adam\Source\Repos\NameParserSharp\NameParser\NameParser\Parser.cs:line 394
at NameParser.HumanName.set_FullName(String value) in c:\Users\Adam\Source\Repos\NameParserSharp\NameParser\NameParser\Parser.cs:line 46
at NameParser.HumanName..ctor(String fullName)
```

**Comment by aeshirey** [comment]
Finally fixed this. If the input is wrapped in parens (eg, `(John Smith)`), it will still be parsed into the `.Nickname` field, and both the `.FirstName` and `.LastName` will be blank; however, it won't crash.
